### ISSUE TITLE
Can't bind to 'fileElements' since it isn't a known property of 'file-explorer'.

### ISSUE THREAD

**Issue by PanwalaVandan** [LukasMarx/angular-file-manager#1]
Can't bind to 'fileElements' since it isn't a known property of 'file-explorer'.
1. If 'file-explorer' is an Angular component and it has 'fileElements' input, then verify that it is part of this module.
2. If 'file-explorer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("der-box;">
  <mat-card style="height: 100%; box-sizing: border-box; padding:0">
    <file-explorer  [ERROR ->][fileElements]="fileElements | async"
                    [path]="currentPath" 
                    ["): ng:///AppModule/AppComponent.html@2:20
Can't bind to 'path' since it isn't a known property of 'file-explorer'.
1. If 'file-explorer' is an Angular component and it has 'path' input, then verify that it is part of this module.
2. If 'file-explorer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("rder-box; padding:0">
    <file-explorer  [fileElements]="fileElements | async"
                    [ERROR ->][path]="currentPath" 
                    [canNavigateUp]="canNavigateUp" 
                    (folde"): ng:///AppModule/AppComponent.html@3:20
Can't bind to 'canNavigateUp' since it isn't a known property of 'file-explorer'.
1. If 'file-explorer' is an Angular component and it has 'canNavigateUp' input, then verify that it is part of this module.
2. If 'file-explorer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("[fileElements]="fileElements | async"
                    [path]="currentPath" 
                    [ERROR ->][canNavigateUp]="canNavigateUp" 
                    (folderAdded)="addFolder($event)"
              "): ng:///AppModule/AppComponent.html@4:20
'file-explorer' is not a known element:
1. If 'file-explorer' is an Angular component, then verify that it is part of this module.
2. If 'file-explorer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" box-sizing: border-box;">
  <mat-card style="height: 100%; box-sizing: border-box; padding:0">
    [ERROR ->]<file-explorer  [fileElements]="fileElements | async"
                    [path]="currentPath" 
     "): ng:///AppModule/AppComponent.html@2:4
    at syntaxError (compiler.js:1021)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14830)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:24018)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:24005)
    at compiler.js:23948
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:23948)
    at compiler.js:23858
    at Object.then (compiler.js:1012)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:23857)

**Comment by PanwalaVandan** [comment]
I get the above error in chrome but no error in the node server there it compiles properly.
Please help

**Comment by LukasMarx** [comment]
This error occurs, because the file-explorer.module is not imported into the app.module.
Please make sure to import the the file-explorer.module (FileExplorerModule) into the app.module:

https://github.com/LukasMarx/angular-file-manager/blob/b6e37948c70f118833f118f4ad87fd25002edf48/src/app/app.module.ts#L14
